# Generated by Django 6.0.6 on 2026-06-10 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        ('quotes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('project_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('Initiated', 'Initiated'), ('Survey Pending', 'Site Survey Pending'), ('Engineering', 'Engineering & Design'), ('Procurement', 'Material Procurement'), ('Installation', 'Installation Ongoing'), ('Testing', 'Testing & Commissioning'), ('Net Metering', 'Net Metering Approval'), ('Completed', 'Completed & Handed Over')], db_index=True, default='Initiated', max_length=50)),
                ('installer_team', models.CharField(blank=True, max_length=100)),
                ('estimated_start_date', models.DateField(blank=True, null=True)),
                ('estimated_completion_date', models.DateField(blank=True, null=True)),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='leads.lead')),
                ('project_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL)),
                ('quote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='quotes.quote')),
            ],
            options={
                'db_table': 'projects_project',
            },
        ),
        migrations.CreateModel(
            name='NetMetering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discom_name', models.CharField(max_length=100)),
                ('application_number', models.CharField(blank=True, max_length=100)),
                ('application_date', models.DateField(blank=True, null=True)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('meter_installation_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='net_metering', to='projects.project')),
            ],
            options={
                'db_table': 'projects_net_metering',
            },
        ),
        migrations.CreateModel(
            name='AMC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amc_contracts', to='projects.project')),
            ],
            options={
                'db_table': 'projects_amc',
            },
        ),
        migrations.CreateModel(
            name='SiteSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_date', models.DateTimeField()),
                ('roof_type', models.CharField(max_length=100)),
                ('available_area_sqft', models.FloatField()),
                ('shading_percentage', models.FloatField(default=0)),
                ('structural_integrity', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='projects.project')),
                ('surveyor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projects_survey',
            },
        ),
    ]
