# Generated by Django 6.0.6 on 2026-06-10 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('quote_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pending Approval', 'Pending Approval'), ('Sent', 'Sent'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Expired', 'Expired')], db_index=True, default='Draft', max_length=50)),
                ('system_type', models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Industrial', 'Industrial')], max_length=50)),
                ('kw_size', models.FloatField()),
                ('panel_tier', models.CharField(default='Standard', max_length=50)),
                ('inverter_type', models.CharField(default='String', max_length=50)),
                ('battery_kwh', models.FloatField(default=0)),
                ('cost_per_kw', models.DecimalField(decimal_places=2, max_digits=10)),
                ('system_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('install_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('battery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amc_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gst_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gst_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subsidy_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('annual_generation_kwh', models.FloatField()),
                ('electricity_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tariff_escalation_rate', models.DecimalField(decimal_places=4, default=0.03, max_digits=5)),
                ('annual_saving', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payback_years', models.FloatField()),
                ('co2_saving_tons', models.FloatField()),
                ('valid_until', models.DateTimeField()),
                ('terms_conditions', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_quotes', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quotes', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='leads.lead')),
            ],
            options={
                'db_table': 'quotes_quote',
                'ordering': ['-created_at'],
            },
        ),
    ]
