# Generated by Django 6.0.5 on 2026-06-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('Website', 'Website'), ('Facebook Ad', 'Facebook Ad'), ('Google Ad', 'Google Ad'), ('Referral', 'Referral'), ('Cold Call', 'Cold Call'), ('WhatsApp', 'WhatsApp'), ('Exhibition', 'Exhibition'), ('Newspaper Ad', 'Newspaper Ad'), ('TV Ad', 'TV Ad'), ('Other', 'Other')], db_index=True, default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Qualified', 'Qualified'), ('Proposal', 'Proposal'), ('Negotiation', 'Negotiation'), ('Won', 'Won'), ('Lost', 'Lost')], db_index=True, default='New', max_length=50),
        ),
    ]
